name: Sync Dev Branch

on:
  pull_request: 
    branches:
      - main

jobs:
  sync-dev:
    runs-on: alpine-latest
    permissions:
      contents: write  # Gives write access to repository contents
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update dev branch
        id: sync
        continue-on-error: true
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout dev
          git merge main
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Feishu notification on success
        if: success()
        run: |
          timestamp=$(date +%s)
          curl -X POST "https://open.feishu.cn/open-apis/bot/v2/hook/0788acac-eb5c-40eb-8409-1da9b244f440" \
          -H "Content-Type: application/json" \
          -d '{
            "msg_type": "interactive",
            "card": {
              "config": { "wide_screen_mode": true },
              "header": {
                "title": { "tag": "plain_text", "content": "✅ Dev Branch Sync Completed" },
                "template": "green"
              },
              "elements": [
                {
                  "tag": "div",
                  "text": {
                    "tag": "lark_md",
                    "content": "✅ **Dev Branch Sync Successful**\n\n**Repository:** ${{ github.repository }}\n**Workflow:** ${{ github.workflow }}\n**Triggered by:** ${{ github.actor }}\n**Event:** ${{ github.event_name }}\n\n[View Action Details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
                  }
                }
              ]
            }
          }'

      - name: Send Feishu notification on failure
        if: failure()
        run: |
          timestamp=$(date +%s)
          curl -X POST "https://open.feishu.cn/open-apis/bot/v2/hook/0788acac-eb5c-40eb-8409-1da9b244f440" \
          -H "Content-Type: application/json" \
          -d '{
            "msg_type": "interactive",
            "card": {
              "config": { "wide_screen_mode": true },
              "header": {
                "title": { "tag": "plain_text", "content": "🚨 Dev Branch Sync Failed" },
                "template": "green"
              },
              "elements": [
                {
                  "tag": "div",
                  "text": {
                    "tag": "lark_md",
                    "content": "❌ **Dev Branch Sync Failed**\n\n**Repository:** ${{ github.repository }}\n**Workflow:** ${{ github.workflow }}\n**Triggered by:** ${{ github.actor }}\n**Event:** ${{ github.event_name }}\n\n[View Action Details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})",
                  }
                }
              ]
            }
          }'